# Generated by Django 5.0 on 2023-12-28 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgName', models.CharField(max_length=30)),
                ('imgPrice', models.IntegerField()),
                ('img', models.ImageField(upload_to='media')),
            ],
        ),
    ]
