# Generated by Django 5.0 on 2024-01-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carApp', '0002_alter_userimage_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='imgMode',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userimage',
            name='imgModel',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userimage',
            name='imgVariant',
            field=models.CharField(default=3, max_length=30),
            preserve_default=False,
        ),
    ]
