# Generated by Django 5.0 on 2024-01-04 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carApp', '0003_userimage_imgmode_userimage_imgmodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userimage',
            old_name='img',
            new_name='imgTake',
        ),
    ]
