# Generated by Django 5.0 on 2024-02-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carApp', '0005_rename_imgtake_userimage_imgpick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='imgPrice',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
