# Generated by Django 5.0 on 2024-02-16 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carApp', '0007_cart_rename_userimage_userproduct_cartitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
    ]
