# Generated by Django 5.0 on 2024-03-14 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carApp', '0008_remove_cart_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
