# Generated by Django 5.0 on 2023-12-31 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pass1',
            new_name='password1',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='pass2',
            new_name='password2',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='uname',
            new_name='username',
        ),
    ]
