# Generated by Django 5.0 on 2024-02-16 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0003_remove_user_password2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password1',
            new_name='password',
        ),
    ]
